// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: test-ui-spotify

#ifndef _TEST_UI_SPOTIFY_UI_H
#define _TEST_UI_SPOTIFY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_spotify;
extern lv_obj_t * ui_backwards;
extern lv_obj_t * ui_forwards;
extern lv_obj_t * ui_playPause;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1935606821);    // assets/spotify-logo-png-7057(1).png
LV_IMG_DECLARE(ui_img_942630693);    // assets/fast-forward-media-control-button(1)(1).png
LV_IMG_DECLARE(ui_img_1094514855);    // assets/fast-forward-media-control-button(1)(1)(1).png
LV_IMG_DECLARE(ui_img_476004375);    // assets/play-and-pause-button(1).png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
